apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # dummy proxy to prevent long timeouts
    proxy_ssl_server_name on;

    server {
        listen    8080;

        proxy_busy_buffers_size   512k;
        proxy_buffers   4 512k;
        proxy_buffer_size   256k;

        location / {
            proxy_pass https://api.openai.com/v1/;
            proxy_set_header Host api.openai.com;
            proxy_connect_timeout 15s;
            proxy_read_timeout 15s;
            proxy_send_timeout 15s;
        }
    }
