#
# https://raw.githubusercontent.com/SocialGouv/kali-data/master/data/index.json
# copy(d.filter(x=>x.active).map(x=>({id:x.id,shortTitle:x.shortTitle,url:x.url,title:x.title,idcc:x.num})))
#

kali = [
    {
        "id": "KALICONT000005635221",
        "shortTitle": "Bâtiment Ouvriers (entreprises occupant jusqu'à 10 salariés)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635221",
        "title": "Nouvelle convention collective nationale des ouvriers employés par les entreprises du bâtiment visées par le décret du 1er mars 1962 (c'est-à-dire occupant jusqu'à 10 salariés) du 7 mars 2018 (Avenant du 7 mars 2018) ",
        "idcc": 1596,
    },
    {
        "id": "KALICONT000005635220",
        "shortTitle": "Bâtiment Ouvriers (entreprises occupant plus de 10 salariés)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635220",
        "title": "Nouvelle convention collective nationale des ouvriers employés par les entreprises du bâtiment non visées par le décret du 1er mars 1962 (c'est-à-dire occupant plus de 10 salariés) du 7 mars 2018 (Avenant du 7 mars 2018)",
        "idcc": 1597,
    },
    {
        "id": "KALICONT000005635186",
        "shortTitle": "Industrie des cuirs et peaux",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635186",
        "title": "Nouvelle convention collective nationale de travail de l'industrie des cuirs et peaux du 6 juin 2018 (Avenant du 6 juin 2018) ",
        "idcc": 207,
    },
    {
        "id": "KALICONT000005635255",
        "shortTitle": "Camping (industries)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635255",
        "title": "Convention collective nationale du camping du 13 janvier 1970 mise à jour par accord du 20 janvier 2015 ",
        "idcc": 1618,
    },
    {
        "id": "KALICONT000005635524",
        "shortTitle": "Métiers de la transformation des grains",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635524",
        "title": "Convention collective nationale des métiers de la transformation des grains du 9 novembre 2016 (Avenant n° 46 du 9 novembre 2016)",
        "idcc": 1930,
    },
    {
        "id": "KALICONT000032494008",
        "shortTitle": "Collaborateurs salariés des entreprises d'économistes de la construction et des métreurs-vérificateurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000032494008",
        "title": "Convention collective nationale des collaborateurs salariés des entreprises d'économistes de la construction et des métreurs-vérificateurs du 16 décembre 2015",
        "idcc": 3213,
    },
    {
        "id": "KALICONT000005635629",
        "shortTitle": "Détaillants en chaussures",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635629",
        "title": "Convention collective nationale des détaillants en chaussures du 27 juin 1973 (actualisée par avenant n° 79 du 8 décembre 2014 étendu par arrêté du 11 décembre 2015 JORF 23 décembre 2015)",
        "idcc": 733,
    },
    {
        "id": "KALICONT000005635851",
        "shortTitle": "Négoce en fournitures dentaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635851",
        "title": "Convention collective nationale du négoce en fournitures dentaires (Accord du 18 novembre 2014 modifiant les dispositions communes et l'annexe II « Avenant Cadres »)",
        "idcc": 635,
    },
    {
        "id": "KALICONT000005635092",
        "shortTitle": "Notariat",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635092",
        "title": "Nouvelle convention collective nationale du notariat du 19 février 2015 (Accord du 19 février 2015 portant actualisation et consolidation de la convention nationale du notariat du 8 juin 2001)",
        "idcc": 2205,
    },
    {
        "id": "KALICONT000027084096",
        "shortTitle": "Entreprises de services à la personne",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027084096",
        "title": "Convention collective nationale des entreprises de services à la personne du 20 septembre 2012",
        "idcc": 3127,
    },
    {
        "id": "KALICONT000005635399",
        "shortTitle": "Agences de voyages et de tourisme : personnels, guides accompagnateurs et accompagnateurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635399",
        "title": "Convention collective nationale de travail du personnel des agences de voyages et de tourisme du 12 mars 1993 (réécrite par avenant du 10 décembre 2013)",
        "idcc": 1710,
    },
    {
        "id": "KALICONT000030264028",
        "shortTitle": "Industrie du bois de pin maritime en forêt de Gascogne",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000030264028",
        "title": "Convention collective interrégionale de l'industrie du bois de pin maritime en forêt de Gascogne du 1er juillet 2014 (réactualisation)",
        "idcc": 172,
    },
    {
        "id": "KALICONT000005635844",
        "shortTitle": "Laboratoires de biologie médicale extrahospitaliers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635844",
        "title": "Convention collective nationale des laboratoires de biologie médicale extra-hospitaliers du 3 février 1978.",
        "idcc": 959,
    },
    {
        "id": "KALICONT000005635653",
        "shortTitle": "Entreprises de la maintenance, distribution et location de matériels agricoles, de travaux publics, de bâtiment, de manutention, de motoculture de plaisance et activités connexes, dite SDLM",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635653",
        "title": "Convention collective nationale métropolitaine des entreprises de la maintenance, distribution et location de matériels agricoles, de travaux publics, de bâtiment, de manutention, de motoculture de plaisance et activités connexes, dite SDLM du 23 avril 2012",
        "idcc": 1404,
    },
    {
        "id": "KALICONT000028059838",
        "shortTitle": "Production cinématographique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000028059838",
        "title": "Convention collective nationale de la production cinématographique du 19 janvier 2012.",
        "idcc": 3097,
    },
    {
        "id": "KALICONT000028157262",
        "shortTitle": "Spectacle vivant (entreprises du secteur privé)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000028157262",
        "title": "Convention collective nationale des entreprises du secteur privé du spectacle vivant du 3 février 2012 ",
        "idcc": 3090,
    },
    {
        "id": "KALICONT000005635438",
        "shortTitle": "Vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635438",
        "title": "Nouvelle convention collective nationale des vins, cidres, jus de fruits, sirops, spiritueux et liqueurs de France du 15 mars 2013",
        "idcc": 493,
    },
    {
        "id": "KALICONT000005635223",
        "shortTitle": "Services de santé au travail interentreprises",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635223",
        "title": "Convention collective nationale des services de santé au travail interentreprises du 20 juillet 1976. Etendue par arrêté du 18 octobre 1976 JORF 29 octobre 1976.",
        "idcc": 897,
    },
    {
        "id": "KALICONT000005635906",
        "shortTitle": "Ports de plaisance",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635906",
        "title": "Convention collective nationale des personnels des ports de plaisance du 8 mars 2012",
        "idcc": 1182,
    },
    {
        "id": "KALICONT000027180935",
        "shortTitle": "Librairie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027180935",
        "title": "Convention collective nationale de la librairie du 24 mars 2011",
        "idcc": 3013,
    },
    {
        "id": "KALICONT000027172335",
        "shortTitle": "Entreprises de propreté et services associés",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027172335",
        "title": "Convention collective nationale des entreprises de propreté et services associés du 26 juillet 2011",
        "idcc": 3043,
    },
    {
        "id": "KALICONT000027199162",
        "shortTitle": "Régies de quartier",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027199162",
        "title": "Convention collective nationale des régies de quartier du 2 avril 2012",
        "idcc": 3105,
    },
    {
        "id": "KALICONT000005635870",
        "shortTitle": "Commerces de détail non alimentaires : antiquités, brocante, galeries d'art (œuvres d'art), arts de la table, coutellerie, droguerie, équipement du foyer, bazars, commerces ménagers, modélisme, jeux, jouets, puérinatalité, maroquinerie, presse et jeux de hasard ou pronostics, produits de la vape",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635870",
        "title": "Convention collective nationale des commerces de détail non alimentaires : antiquités, brocante, galeries d'art (œuvres d'art), arts de la table, coutellerie, droguerie, équipement du foyer, bazars, commerces ménagers, modélisme, jeux, jouets, puérinatalité et maroquinerie du 9 mai 2012 (avenant du 9 mai 2012)",
        "idcc": 1517,
    },
    {
        "id": "KALICONT000026950865",
        "shortTitle": "Établissements médico-sociaux de l'union intersyndicale des secteurs sanitaires et sociaux",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000026950865",
        "title": "Convention relative aux établissements médico-sociaux de l'union intersyndicale des secteurs sanitaires et sociaux (Avenant du 16 mars 2012 relatif à la mise à jour de la convention)",
        "idcc": 405,
    },
    {
        "id": "KALICONT000025844703",
        "shortTitle": "Entreprises de navigation : personnel sédentaire",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025844703",
        "title": "Convention collective nationale du personnel sédentaire des entreprises de navigation du 14 septembre 2010",
        "idcc": 2972,
    },
    {
        "id": "KALICONT000027065067",
        "shortTitle": "Parfumerie, esthétique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027065067",
        "title": "Convention collective nationale de l'esthétique-cosmétique et de l'enseignement technique et professionnel lié aux métiers de l'esthétique et de la parfumerie du 24 juin 2011 ",
        "idcc": 3032,
    },
    {
        "id": "KALICONT000029142476",
        "shortTitle": "Ports et manutention",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000029142476",
        "title": "Convention collective nationale unifiée ports et manutention du 15 avril 2011",
        "idcc": 3017,
    },
    {
        "id": "KALICONT000005635612",
        "shortTitle": "Entreprises de commission, de courtage et de commerce intracommunautaire et d'importation-exportation de France métropolitaine (CCNIE)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635612",
        "title": "Convention collective nationale des entreprises de commission, de courtage et de commerce intracommunautaire et d'importation-exportation du 18 décembre 1952.  Etendue par arrêté du 18 octobre 1955 JORF 6 novembre 1955 rectificatif JORF 22 novembre 1955",
        "idcc": 43,
    },
    {
        "id": "KALICONT000027181035",
        "shortTitle": "Ateliers et chantiers d'insertion",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000027181035",
        "title": "Convention collective nationale des ateliers et chantiers d'insertion du 31 mars 2011 ",
        "idcc": 3016,
    },
    {
        "id": "KALICONT000005635181",
        "shortTitle": "Construction-promotion",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635181",
        "title": "Convention collective nationale de la promotion immobilière du 18 mai 1988.  Etendue par arrêté du 4 novembre 1988 JORF 15 novembre 1988.",
        "idcc": 1512,
    },
    {
        "id": "KALICONT000025393730",
        "shortTitle": "Métallurgie : Gironde et Landes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025393730",
        "title": "Convention collective des industries métallurgiques, mécaniques et connexes (Gironde et Landes) Mise à jour par avenant du 18 février 2011",
        "idcc": 1635,
    },
    {
        "id": "KALICONT000005635640",
        "shortTitle": "Commerces de gros de l'habillement, de la mercerie, de la chaussure et du jouet",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635640",
        "title": "Convention collective des commerces de gros de l'habillement, de la mercerie, de la chaussure et du jouet du 13 mars 1969.  Etendue par arrêté du 2 novembre 1970 JONC 13 décembre 1970.",
        "idcc": 500,
    },
    {
        "id": "KALICONT000005635413",
        "shortTitle": "Immobilier : administrateurs de biens, sociétés immobilières, agents immobiliers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635413",
        "title": "Convention collective nationale de l'immobilier, administrateurs de biens, sociétés immobilières, agents immobiliers, etc. (anciennement cabinets d'administrateurs de biens et des sociétés immobilières), du 9 septembre 1988. Etendue par arrêté du 24 février 1989 JORF 3 mars 1989. Mise à jour par avenant  n° 47 du 23 novembre 2010, JORF 18 juillet 2012 ",
        "idcc": 1527,
    },
    {
        "id": "KALICONT000005635411",
        "shortTitle": "Activités de production des eaux embouteillées, de boissons rafraîchissantes sans alcool et de bière",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635411",
        "title": "Convention collective nationale des activités de production des eaux embouteillées et boissons rafraîchissantes sans alcool et de bière du 1er septembre 2010. Etendue par arrêté du 30 mai 2012 JORF 06 juin 2012.",
        "idcc": 1513,
    },
    {
        "id": "KALICONT000025496787",
        "shortTitle": "Activités de marchés financiers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025496787",
        "title": "Convention collective nationale des activités de marchés financiers du 11 juin 2010",
        "idcc": 2931,
    },
    {
        "id": "KALICONT000025805800",
        "shortTitle": "Aide, accompagnement, soins et services à domicile (BAD)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025805800",
        "title": "Convention collective nationale de la branche de l'aide, de l'accompagnement, des soins et des services à domicile du 21 mai 2010",
        "idcc": 2941,
    },
    {
        "id": "KALICONT000025278390",
        "shortTitle": "Pôle emploi",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025278390",
        "title": "Convention collective nationale de Pôle emploi du 21 novembre 2009. Étendue par arrêté du 19 février 2010 JORF 24 février 2010. Agréée par arrêté du 21 décembre 2009 JORF 27 décembre 2009",
        "idcc": 2847,
    },
    {
        "id": "KALICONT000019901252",
        "shortTitle": "Portage de presse",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019901252",
        "title": "Convention collective nationale du portage de presse du 26 juin 2007",
        "idcc": 2683,
    },
    {
        "id": "KALICONT000005635953",
        "shortTitle": "Gardiens, concierges et employés d'immeubles",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635953",
        "title": "Convention collective nationale des gardiens, concierges et employés d'immeubles (réécrite par l'avenant n° 74 du 27 avril 2009 portant modification de la convention)",
        "idcc": 1043,
    },
    {
        "id": "KALICONT000021636922",
        "shortTitle": "Sociétés de ventes volontaires de meubles aux enchères publiques et des offices de commissaires-priseurs judiciaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000021636922",
        "title": "Convention collective nationale des sociétés de ventes volontaires de meubles aux enchères publiques et des offices de commissaires-priseurs judiciaires du 17 décembre 2008",
        "idcc": 2785,
    },
    {
        "id": "KALICONT000019765628",
        "shortTitle": "Magasins prestataires de services de cuisine à usage domestique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019765628",
        "title": "Convention collective nationale des magasins prestataires de services de cuisine à usage domestique du  17 juillet 2008&#13;\n&#13;\n",
        "idcc": 2754,
    },
    {
        "id": "KALICONT000023974024",
        "shortTitle": "Édition phonographique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000023974024",
        "title": "Convention collective nationale de l'edition phonographique du 30 juin 2008 ",
        "idcc": 2770,
    },
    {
        "id": "KALICONT000023822189",
        "shortTitle": "Régime social des indépendants Employés et cadres",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000023822189",
        "title": "Convention collective nationale des employés et cadres du régime social des indépendants du 20 mars 2008",
        "idcc": 2798,
    },
    {
        "id": "KALICONT000019906603",
        "shortTitle": "Entreprises techniques au service de la création et de l'événement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019906603",
        "title": "Convention collective nationale des entreprises techniques au service de la création et de l'événement du 21 février 2008",
        "idcc": 2717,
    },
    {
        "id": "KALICONT000024794551",
        "shortTitle": "Bâtiment ETAM (Ile-de-France)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000024794551",
        "title": "Convention collective régionale des employés, techniciens et agents de maîtrise du bâtiment de la région Ile-de-France (hors Seine-et-Marne) du 19 novembre 2007",
        "idcc": 2707,
    },
    {
        "id": "KALICONT000025196564",
        "shortTitle": "Sucreries, sucreries-distilleries et raffineries de sucre",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000025196564",
        "title": "Convention collective nationale des sucreries, sucreries-distilleries et raffineries de sucre du 31 janvier 2008",
        "idcc": 2728,
    },
    {
        "id": "KALICONT000005635592",
        "shortTitle": "Quincaillerie : commerces de quincaillerie, fournitures industrielles, fers-métaux et équipements de la maison",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635592",
        "title": "Convention collective nationale des cadres des commerces de quincaillerie, fournitures industrielles, fers, métaux et équipement de la maison du 23 juin 1971 (anciennement convention collective interrégionale). Etendue par arrêté du 13 juillet 1973 JORF 9 septembre 1973.",
        "idcc": 731,
    },
    {
        "id": "KALICONT000019647748",
        "shortTitle": "Administrateurs et mandataires judiciaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019647748",
        "title": "Convention collective nationale du personnel des administrateurs et des mandataires judiciaires du 20 décembre 2007",
        "idcc": 2706,
    },
    {
        "id": "KALICONT000019593660",
        "shortTitle": "Enseignement privé indépendant",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019593660",
        "title": "Convention collective nationale de l'enseignement privé indépendant du 27 novembre 2007 ",
        "idcc": 2691,
    },
    {
        "id": "KALICONT000018773893",
        "shortTitle": "Bâtiment ETAM",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018773893",
        "title": "Convention collective nationale des employés, techniciens et agents de maîtrise du bâtiment du 12 juillet 2006",
        "idcc": 2609,
    },
    {
        "id": "KALICONT000020089210",
        "shortTitle": "Conseils d'architecture, d'urbanisme et de l'environnement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000020089210",
        "title": "Convention collective nationale des conseils d'architecture, d'urbanisme et de l'environnement du 24 mai 2007",
        "idcc": 2666,
    },
    {
        "id": "KALICONT000018563755",
        "shortTitle": "Coiffure et professions connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018563755",
        "title": "Convention collective nationale de la coiffure et des professions connexes du 10 juillet 2006. Etendue par arrêté du 3 avril 2007 JORF 17 avril 2007.",
        "idcc": 2596,
    },
    {
        "id": "KALICONT000005635375",
        "shortTitle": "Charcuterie de détail",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635375",
        "title": "Convention collective nationale de la charcuterie de détail du 4 avril 2007",
        "idcc": 953,
    },
    {
        "id": "KALICONT000018828041",
        "shortTitle": "Production audiovisuelle",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018828041",
        "title": "Convention collective nationale de la production audiovisuelle du 13 décembre 2006",
        "idcc": 2642,
    },
    {
        "id": "KALICONT000018926209",
        "shortTitle": "Travaux publics (Tome III : ETAM)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018926209",
        "title": "Convention collective nationale des employés, techniciens et agents de maîtrise des travaux publics du 12 juillet 2006",
        "idcc": 2614,
    },
    {
        "id": "KALICONT000005635593",
        "shortTitle": "Boucherie, boucherie-charcuterie, boucherie hippophagique, triperie, commerces de volailles et gibiers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635593",
        "title": "Convention collective nationale de la boucherie, boucherie-charcuterie, boucherie hippophagique, triperie, commerces de volailles et gibiers du 12 décembre 1978, actualisée",
        "idcc": 992,
    },
    {
        "id": "KALICONT000018977636",
        "shortTitle": "Sociétés concessionnaires ou exploitantes d'autoroutes ou d'ouvrages routiers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018977636",
        "title": "Convention collective nationale des sociétés concessionnaires ou exploitantes d'autoroutes ou d'ouvrages routiers du 27 juin 2006 ",
        "idcc": 2583,
    },
    {
        "id": "KALICONT000005635449",
        "shortTitle": "Lait : industrie laitière",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635449",
        "title": "Convention collective nationale de l'industrie laitière du 20 mai 1955, modifiée par avenant n° 34 du 29 juin 2006. Etendue par arrêté du 10 décembre 2007 JORF 18 décembre 2007",
        "idcc": 112,
    },
    {
        "id": "KALICONT000005635824",
        "shortTitle": "Vétérinaires (praticiens salariés)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635824",
        "title": "Convention collective nationale des vétérinaires praticiens salariés du 31 janvier 2006",
        "idcc": 2564,
    },
    {
        "id": "KALICONT000005635410",
        "shortTitle": "Poissonnerie (commerce de détail, demi-gros et gros)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635410",
        "title": "Convention collective nationale de la poissonnerie mise à jour par l'avenant du 12 janvier 2006 ",
        "idcc": 1504,
    },
    {
        "id": "KALICONT000019938657",
        "shortTitle": "Métallurgie : Aisne (industries métallurgiques, mécaniques et connexes)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000019938657",
        "title": "Convention collective départementale des industries métallurgiques, mécaniques et connexes de l'Aisne du 30 septembre 2005",
        "idcc": 2542,
    },
    {
        "id": "KALICONT000005635804",
        "shortTitle": "Cabinets ou entreprises de géomètres-experts, géomètres-topographes, photogrammètres et experts fonciers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635804",
        "title": "Convention collective nationale des cabinets ou entreprises de géomètres-experts, géomètres-topographes, photogrammètres et experts fonciers du 13 octobre 2005.  Etendue par arrêté du 24 juillet 2006 JORF 2 août 2006.",
        "idcc": 2543,
    },
    {
        "id": "KALICONT000005635109",
        "shortTitle": "Maroquinerie, articles de voyage, chasse sellerie, gainerie, bracelets en cuir : industries",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635109",
        "title": "Convention collective nationale des industries de la maroquinerie, articles de voyage, chasse-sellerie, gainerie, bracelets en cuir du 9 septembre 2005.  Etendue par arrêté du 12 juin 2006 JORF 23 juin 2006.",
        "idcc": 2528,
    },
    {
        "id": "KALICONT000017577652",
        "shortTitle": "Sport",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000017577652",
        "title": "Convention collective nationale du sport du 7 juillet 2005 étendue par arrêté du 21 novembre 2006",
        "idcc": 2511,
    },
    {
        "id": "KALICONT000005635594",
        "shortTitle": "Commerce de détail de l'habillement et des articles textiles",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635594",
        "title": "Convention collective nationale du commerce de détail de l'habillement et des articles textiles du 25 novembre 1987, révisée par avenant du 17 juin 2004",
        "idcc": 1483,
    },
    {
        "id": "KALICONT000018563634",
        "shortTitle": "Coopération maritime",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018563634",
        "title": "Convention collective nationale de la coopération maritime du 7 décembre 2004 (réécrite par avenant n° 8 du 23 novembre 2011) ",
        "idcc": 2494,
    },
    {
        "id": "KALICONT000017941839",
        "shortTitle": "Bâtiment Cadres",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000017941839",
        "title": "Convention collective nationale des cadres du bâtiment du 1er juin 2004",
        "idcc": 2420,
    },
    {
        "id": "KALICONT000005635840",
        "shortTitle": "Industries de produits alimentaires élaborés",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635840",
        "title": "Convention collective nationale pour les industries de produits alimentaires élaborés du 17 janvier 1952. Mise à jour par accord du 22 octobre 1985. Etendue par arrêté du 16 avril 1986 JORF 25 avril 1986.",
        "idcc": 1396,
    },
    {
        "id": "KALICONT000005635585",
        "shortTitle": "Chaînes thématiques",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635585",
        "title": "Convention collective nationale des chaînes thématiques du 23 juillet 2004.  Etendue par arrêté 4 juillet 2005 JORF 19 juillet 2005.",
        "idcc": 2411,
    },
    {
        "id": "KALICONT000005635129",
        "shortTitle": "Production de films d'animation",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635129",
        "title": "Convention collective nationale de la production de films d'animation du 6 juillet 2004.  Etendue par arrêté du 18 juillet 2005 JORF 26 juillet 2005.",
        "idcc": 2412,
    },
    {
        "id": "KALICONT000044594539",
        "shortTitle": "Particuliers employeurs et emploi à domicile",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000044594539",
        "title": "Convention collective nationale des particuliers employeurs et de l'emploi à domicile du 15 mars 2021 - Étendue par arrêté du 6 octobre 2021 JORF 16 octobre 2021",
        "idcc": 3239,
    },
    {
        "id": "KALICONT000005635128",
        "shortTitle": "Distribution directe",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635128",
        "title": "Convention collective nationale de la distribution directe du 9 février 2004.  Etendue par arrêté du 16 juillet 2004 JORF 28 juillet 2004.",
        "idcc": 2372,
    },
    {
        "id": "KALICONT000005635560",
        "shortTitle": "Organismes gestionnaires de foyers et services pour jeunes travailleurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635560",
        "title": "Convention collective nationale des organismes gestionnaires de foyers et services pour jeunes travailleurs du 16 juillet 2003.  ",
        "idcc": 2336,
    },
    {
        "id": "KALICONT000005635361",
        "shortTitle": "Personnels des agences générales d'assurances",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635361",
        "title": "Convention collective nationale du personnel des agences générales d'assurances du 2 juin 2003. Etendue par arrêté du 9 décembre 2003 JORF 18 décembre 2003  ",
        "idcc": 2335,
    },
    {
        "id": "KALICONT000005635365",
        "shortTitle": "Entreprises d'architecture",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635365",
        "title": "Convention collective nationale des entreprises d'architecture du 27 février 2003.  Etendue par arrêté du 6 janvier 2004 JORF 16 janvier 2004.",
        "idcc": 2332,
    },
    {
        "id": "KALICONT000005635133",
        "shortTitle": "Assainissement et maintenance industrielle",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635133",
        "title": "Convention collective nationale de l'assainissement et de la maintenance industrielle du 21 mai 2002.  Etendue par arrêté du 26 octobre 2004 JORF 9 novembre 2004.",
        "idcc": 2272,
    },
    {
        "id": "KALICONT000005635813",
        "shortTitle": "Hospitalisation privée",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635813",
        "title": "Convention collective nationale de l'hospitalisation privée du 18 avril 2002",
        "idcc": 2264,
    },
    {
        "id": "KALICONT000005635618",
        "shortTitle": "Casinos",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635618",
        "title": "Convention collective nationale des casinos du 29 mars 2002. Etendue par arrêté du 2 avril 2003 JORF 29 avril 2003.",
        "idcc": 2257,
    },
    {
        "id": "KALICONT000005635720",
        "shortTitle": "Entreprises de courtage d'assurances et/ou de réassurances",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635720",
        "title": "Convention collective nationale des entreprises de courtage d'assurances et/ou de réassurances du 18 janvier 2002, étendue par arrêté du 14 octobre 2002 (JO du 25 octobre 2002)",
        "idcc": 2247,
    },
    {
        "id": "KALICONT000021284958",
        "shortTitle": "Sidérurgie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000021284958",
        "title": "Convention collective nationale de la sidérurgie du 20 novembre 2001",
        "idcc": 2344,
    },
    {
        "id": "KALICONT000021125058",
        "shortTitle": "Taxis",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000021125058",
        "title": "Convention collective nationale des taxis du 11 septembre 2001",
        "idcc": 2219,
    },
    {
        "id": "KALICONT000005635782",
        "shortTitle": "Activités du déchet",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635782",
        "title": "Convention collective nationale des activités du déchet du 11 mai 2000.  Etendue par arrêté du 5 juillet 2001 JORF 17 juillet 2001",
        "idcc": 2149,
    },
    {
        "id": "KALICONT000005635085",
        "shortTitle": "Commerce de détail et de gros à prédominance alimentaire",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635085",
        "title": "Convention collective nationale du commerce de détail et de gros à prédominance alimentaire du 12 juillet 2001.  Etendue par arrêté du 26 juillet 2002 JORF 6 août 2002.",
        "idcc": 2216,
    },
    {
        "id": "KALICONT000005635091",
        "shortTitle": "Missions locales et PAIO",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635091",
        "title": "Convention collective nationale des missions locales et PAIO du 21 février 2001. (Etendue par arrêté du 27 décembre 2001 JO du 1er janvier 2002) (1)",
        "idcc": 2190,
    },
    {
        "id": "KALICONT000005635798",
        "shortTitle": "Entreprises de vente à distance",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635798",
        "title": "Convention collective nationale des entreprises du commerce à distance du 6 février 2001  ",
        "idcc": 2198,
    },
    {
        "id": "KALICONT000005635557",
        "shortTitle": "Télécommunications",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635557",
        "title": "Convention collective nationale des télécommunications du 26 avril 2000",
        "idcc": 2148,
    },
    {
        "id": "KALICONT000005635584",
        "shortTitle": "Navigation intérieure : personnel sédentaire (cadres et ETAM)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635584",
        "title": "Convention collective nationale du personnel sédentaire des entreprises de transport de marchandises de la navigation intérieure (3 annexes) du 5 septembre 2000.  Etendue par arrêté du 10 avril 2002 JORF 3 mai 2002.",
        "idcc": 2174,
    },
    {
        "id": "KALICONT000005635093",
        "shortTitle": "Grands magasins et magasins populaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635093",
        "title": "Convention collective nationale des grand magasins et des magasins populaires du 30 juin 2000.  Etendue par arrêté du 20 décembre 2001 JORF 19 janvier 2002.",
        "idcc": 2156,
    },
    {
        "id": "KALICONT000005635331",
        "shortTitle": "Personnels des sociétés anonymes et fondations d'HLM",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635331",
        "title": "Convention collective nationale des personnels des sociétés anonymes et fondations d'HLM du 27 avril 2000.  Etendue par arrêté du 22 janvier 2001 JORF 6 février 2001.",
        "idcc": 2150,
    },
    {
        "id": "KALICONT000005635338",
        "shortTitle": "Entreprises des services d'eau et d'assainissement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635338",
        "title": "Convention collective nationale des entreprises des services d'eau et d'assainissement du 12 avril 2000",
        "idcc": 2147,
    },
    {
        "id": "KALICONT000005635550",
        "shortTitle": "Prestataires de services dans le domaine du secteur tertiaire",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635550",
        "title": "Convention collective nationale du personnel des prestataires de services dans le domaine du secteur tertiaire du 13 août 1999",
        "idcc": 2098,
    },
    {
        "id": "KALICONT000005635784",
        "shortTitle": "Mutualité",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635784",
        "title": "Convention collective nationale de la mutualité du 31 janvier 2000.  Etendue par arrêté du 17 août 2001 JORF 28 août 2001",
        "idcc": 2128,
    },
    {
        "id": "KALICONT000005635096",
        "shortTitle": "Édition",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635096",
        "title": "Convention collective nationale de l'édition du 14 janvier 2000",
        "idcc": 2121,
    },
    {
        "id": "KALICONT000005635780",
        "shortTitle": "Banque",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635780",
        "title": "Convention collective nationale de la banque du 10 janvier 2000.  Etendue par arrêté du 17 novembre 2004 JORF 11 décembre 2004.",
        "idcc": 2120,
    },
    {
        "id": "KALICONT000005635545",
        "shortTitle": "Thermalisme",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635545",
        "title": "Convention collective nationale du thermalisme du 10 septembre 1999.  Etendue par arrêté du 2 mars 2000 JORF 11 mars 2000.",
        "idcc": 2104,
    },
    {
        "id": "KALICONT000005635326",
        "shortTitle": "Cafétérias et assimilés (chaînes)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635326",
        "title": "Convention collective nationale des chaînes de cafétérias et assimilés du 28 août 1998. Etendue par arrêté du 20 décembre 1999 JORF 29 décembre 1999",
        "idcc": 2060,
    },
    {
        "id": "KALICONT000005635337",
        "shortTitle": "Industrie des panneaux à base de bois",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635337",
        "title": "Convention collective nationale de l'industrie des panneaux à base de bois du 29 juin 1999",
        "idcc": 2089,
    },
    {
        "id": "KALICONT000005635097",
        "shortTitle": "Œufs et industries en produits d’œufs (centres de conditionnement, de commercialisation et de transformation)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635097",
        "title": "Convention collective nationale des centres immatriculés de conditionnement, de commercialisation et de transformation des œufs et des industries en produits d'œufs du 10 mai 1999. Etendue par arrêté du 2 août 1999 JORF 10 août 1999",
        "idcc": 2075,
    },
    {
        "id": "KALICONT000005635559",
        "shortTitle": "Golf",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635559",
        "title": "Convention collective nationale du golf du 13 juillet 1998",
        "idcc": 2021,
    },
    {
        "id": "KALICONT000021213367",
        "shortTitle": "Centres de lutte contre le cancer",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000021213367",
        "title": "Convention collective nationale des centres de lutte contre le cancer du 1er janvier 1999",
        "idcc": 2046,
    },
    {
        "id": "KALICONT000005635528",
        "shortTitle": "Pharmacie d'officine",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635528",
        "title": "Convention collective nationale de la pharmacie d'officine du 3 décembre 1997.  Etendue par arrêté du 13 août 1998 (JO du 8 septembre 1998).",
        "idcc": 1996,
    },
    {
        "id": "KALICONT000005636009",
        "shortTitle": "Cabinets ou entreprises d'expertises en automobile",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005636009",
        "title": "Convention collective nationale des cabinets ou entreprises d'expertises en automobile du 20 novembre 1996.  Etendue par arrêté du 8 avril 1998 JORF 24 avril 1998.",
        "idcc": 1951,
    },
    {
        "id": "KALICONT000005636023",
        "shortTitle": "Négoce et prestations de services dans les domaines médico-techniques",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005636023",
        "title": "Convention collective nationale du négoce et des prestations de services dans les domaines médico-techniques du 9 avril 1997",
        "idcc": 1982,
    },
    {
        "id": "KALICONT000005635534",
        "shortTitle": "Hôtels, cafés, restaurants",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635534",
        "title": "Convention collective nationale des hôtels, cafés restaurants (HCR) du 30 avril 1997",
        "idcc": 1979,
    },
    {
        "id": "KALICONT000005635491",
        "shortTitle": "Blanchisserie, laverie, location de linge, nettoyage à sec, pressing et teinturerie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635491",
        "title": "Convention collective nationale de la  blanchisserie – teinturerie et nettoyage (blanchisserie, laverie, location de linge, nettoyage à sec, pressing et teinturerie) du 17 novembre 1997.  Etendue par arrêté du 10 août 1998 JORF 20 août 1998",
        "idcc": 2002,
    },
    {
        "id": "KALICONT000005635758",
        "shortTitle": "Pâtes alimentaires sèches et couscous non préparé",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635758",
        "title": "Convention collective nationale des pâtes alimentaires sèches et du couscous non préparé du 3 juillet 1997.  Etendue par arrêté du 3 mars 1998 JORF 12 mars 1998.",
        "idcc": 1987,
    },
    {
        "id": "KALICONT000005635578",
        "shortTitle": "Navigation intérieure : personnel des entreprises de transport de passagers en navigation intérieure",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635578",
        "title": "Convention collective nationale du personnel des entreprises de transport de passagers en navigation intérieure du 23 avril 1997.  Etendue par arrêté du 9 décembre 1997 JORF 20 décembre 1997.",
        "idcc": 1974,
    },
    {
        "id": "KALICONT000005635507",
        "shortTitle": "Fleuristes, vente et services des animaux familiers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635507",
        "title": "Convention collective nationale des fleuristes, de la vente et des services des animaux familiers du 21 janvier 1997.  Etendue par arrêté du 7 octobre 1997 JORF 21 octobre 1997.",
        "idcc": 1978,
    },
    {
        "id": "KALICONT000005635751",
        "shortTitle": "Négoce de bois d'œuvre et produits dérivés",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635751",
        "title": "Convention collective nationale du négoce de bois d'oeuvre et de produits dérivés du 17 décembre 1996.  (Etendue par arrêté du 7 mai 1997, JO du 17 mai 1997)",
        "idcc": 1947,
    },
    {
        "id": "KALICONT000005635523",
        "shortTitle": "Exploitation d'hélicoptères",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635523",
        "title": "Convention collective nationale du personnel navigant technique des exploitants d'hélicoptères du 13 novembre 1996.  Etendue par arrêté du 8 septembre 1997 JORF 25 septembre 1997.",
        "idcc": 1944,
    },
    {
        "id": "KALICONT000005635284",
        "shortTitle": "Industries de la transformation des volailles",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635284",
        "title": "Convention collective nationale des industries de la transformation des volailles du 10 juillet 1996",
        "idcc": 1938,
    },
    {
        "id": "KALICONT000005636003",
        "shortTitle": "Textiles artificiels et synthétiques et produits assimilés",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005636003",
        "title": "Convention collective nationale des textiles artificiels et synthétiques et produits assimilés du 6 juin 1996.  Etendue par arrêté du 29 avril 1998 JORF 14 mai 1998.",
        "idcc": 1942,
    },
    {
        "id": "KALICONT000005635741",
        "shortTitle": "Radiodiffusion",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635741",
        "title": "Convention collective nationale de la radiodiffusion du 11 avril 1996 (accord d'étape) du 11 avril 1996.  Etendue par arrêté du 22 octobre 1996 JORF 1er novembre 1996.",
        "idcc": 1922,
    },
    {
        "id": "KALICONT000005635521",
        "shortTitle": "Personnel des huissiers de justice",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635521",
        "title": "Convention collective nationale du personnel des huissiers de justice du 11 avril 1996.  Etendue par arrêté du 18 octobre 1996 JORF 29 octobre 1996.",
        "idcc": 1921,
    },
    {
        "id": "KALICONT000005635728",
        "shortTitle": "Organismes de tourisme",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635728",
        "title": "Convention collective nationale des organismes de tourisme du 5 février 1996.  Etendue par arrêté du 6 décembre 1996 JORF 19 décembre 1996.",
        "idcc": 1909,
    },
    {
        "id": "KALICONT000005635994",
        "shortTitle": "Vétérinaires : personnel salarié des cabinets et cliniques vétérinaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635994",
        "title": "Convention collective nationale des cabinets et cliniques vétérinaires du 5 juillet 1995.  Etendue par arrêté du 16 janvier 1996 JORF 24 janvier 1996. ",
        "idcc": 1875,
    },
    {
        "id": "KALICONT000005635115",
        "shortTitle": "Négoce de l'ameublement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635115",
        "title": "Convention collective nationale du négoce de l'ameublement du 31 mai 1995",
        "idcc": 1880,
    },
    {
        "id": "KALICONT000005636008",
        "shortTitle": "Avocats : avocats salariés des cabinets",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005636008",
        "title": "Convention collective nationale des cabinets d'avocats (avocats salariés) du 17 février 1995.  Etendue par arrêté du 10 juin 1996 JORF 28 juin 1996.",
        "idcc": 1850,
    },
    {
        "id": "KALICONT000018902144",
        "shortTitle": "Fabrication du verre à la main semi-automatique et mixte",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000018902144",
        "title": "Convention collective nationale de la fabrication du verre à la main, semi-automatique et mixte du 3 novembre 1994.  Etendue par arrêté du 27 janvier 1998 JORF 6 février 1998.",
        "idcc": 1821,
    },
    {
        "id": "KALICONT000005635938",
        "shortTitle": "Jardineries et graineteries",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635938",
        "title": "Convention collective nationale des jardineries et graineteries du 3 décembre 1993.  Etendue par arrêté du 6 juillet 1994 JORF 20 juillet 1994.",
        "idcc": 1760,
    },
    {
        "id": "KALICONT000005635497",
        "shortTitle": "Sociétés d'assistance",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635497",
        "title": "Convention collective nationale des sociétés d'assistance du 13 avril 1994. Etendue par arrêté du 8 février 1995 JORF 18 février 1995",
        "idcc": 1801,
    },
    {
        "id": "KALICONT000005635453",
        "shortTitle": "Espaces de loisirs, d'attractions et culturels (CCNELAC)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635453",
        "title": "Convention collective nationale des espaces de loisirs, d'attractions et culturels du 5 janvier 1994",
        "idcc": 1790,
    },
    {
        "id": "KALICONT000005635247",
        "shortTitle": "Commerce de gros des tissus, tapis et linge de maison",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635247",
        "title": "Convention collective nationale du commerce de gros des tissus, tapis et linge de maison du 15 décembre 1993",
        "idcc": 1761,
    },
    {
        "id": "KALICONT000005635698",
        "shortTitle": "Institutions de retraite complémentaire (personnel)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635698",
        "title": "Convention collective nationale du travail du personnel des institutions de retraites complémentaires du 9 décembre 1993.  Etendue par arrêté du 19 septembre 1994 JORF 29 septembre 1994 et élargie aux institutions de prévoyance par arrêté du 31 janvier 1995 JORF 10 février 1995.",
        "idcc": 1794,
    },
    {
        "id": "KALICONT000005635691",
        "shortTitle": "Activités industrielles de boulangerie et pâtisserie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635691",
        "title": "Convention collective nationale des activités industrielles de boulangerie et pâtisserie du 13 juillet 1993. Mise à jour par avenant n°10 du 11 octobre 2011.",
        "idcc": 1747,
    },
    {
        "id": "KALICONT000005635917",
        "shortTitle": "Maisons d'étudiants",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635917",
        "title": "Convention collective nationale des maisons d'étudiants du 27 mai 1992.  Etendue par arrêté du 20 août 1993 JORF 29 septembre 1993.",
        "idcc": 1671,
    },
    {
        "id": "KALICONT000005635252",
        "shortTitle": "Hôtellerie de plein air",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635252",
        "title": "Convention collective nationale de l'hôtellerie de plein air du 2 juin 1993",
        "idcc": 1631,
    },
    {
        "id": "KALICONT000005635467",
        "shortTitle": "Travaux publics (Tome II : Ouvriers)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635467",
        "title": "Convention collective nationale des ouvriers des travaux publics du 15 décembre 1992",
        "idcc": 1702,
    },
    {
        "id": "KALICONT000005635164",
        "shortTitle": "Commerces et services de l'audiovisuel, de l'électronique et de l'équipement ménager",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635164",
        "title": "Convention collective nationale des commerces et services de l'audiovisuel, de l'électronique et de l'équipement ménager du 26 novembre 1992. Etendue par arrêté du 9 mars 1993 JORF 19 mars 1993.",
        "idcc": 1686,
    },
    {
        "id": "KALICONT000005635475",
        "shortTitle": "Inspection d'assurance",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635475",
        "title": "Convention collective nationale de l'inspection d'assurance du 27 juillet 1992. Etendue par arrêté du 12 juillet 1993 JORF 7 août 1993",
        "idcc": 1679,
    },
    {
        "id": "KALICONT000005635232",
        "shortTitle": "Répartition pharmaceutique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635232",
        "title": "Convention collective nationale de la répartition pharmaceutique du 7 janvier 1992.  Etendue par arrêté du 28 juillet 1992 JORF 29 juillet 1992.",
        "idcc": 1621,
    },
    {
        "id": "KALICONT000005635918",
        "shortTitle": "Sociétés d'assurances",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635918",
        "title": "Convention collective nationale des sociétés d'assurances du 27 mai 1992",
        "idcc": 1672,
    },
    {
        "id": "KALICONT000005635655",
        "shortTitle": "Cabinets dentaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635655",
        "title": "Convention collective nationale des cabinets dentaires du 17 janvier 1992 ",
        "idcc": 1619,
    },
    {
        "id": "KALICONT000005635437",
        "shortTitle": "Entreprises de désinfection, désinsectisation et dératisation (3D)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635437",
        "title": "Convention collective nationale des entreprises de désinfection, désinsectisation, dératisation (3D) du 1er septembre 1991.  Etendue par arrêté du 16 janvier 1992 JORF 31 janvier 1992.",
        "idcc": 1605,
    },
    {
        "id": "KALICONT000005635225",
        "shortTitle": "Commerce de gros de la confiserie, chocolaterie, biscuiterie et alimentation fine et des négociants-distributeurs de levure",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635225",
        "title": "Convention collective nationale du commerce de gros de la confiserie, chocolaterie , biscuiterie et alimentation fine et des négociants-distributeurs de levure du 1er  janvier 1985.  Etendue par arrêté du 7 août 1985 JORF 17 août 1985.",
        "idcc": 1624,
    },
    {
        "id": "KALICONT000005635474",
        "shortTitle": "Publicité directe : entreprises de logistique en publicité directe",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635474",
        "title": "Convention collective nationale des entreprises de logistique de communication écrite directe du 19 novembre 1991.  Etendue par arrêté du 28 avril 1992 JORF 14 mai 1992.(1)",
        "idcc": 1611,
    },
    {
        "id": "KALICONT000023278100",
        "shortTitle": "Métallurgie (Loir-et-Cher)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000023278100",
        "title": "Convention collective  des industries métallurgiques et connexes de Loir-et-Cher du 5 juillet 1991",
        "idcc": 2579,
    },
    {
        "id": "KALICONT000005635904",
        "shortTitle": "Industries des jeux, jouets, articles de fêtes et ornements de Noël, articles de puériculture et voitures d'enfants, modélisme et industries connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635904",
        "title": "Convention collective nationale des industries des jeux, jouets, articles de fêtes et ornements de Nöel, articles de puériculture et voitures d'enfants, modélisme et industries connexes du 25 janvier 1991.  Etendue par arrêté du 8 juillet 1991 JORF 19 juillet 1991.",
        "idcc": 1607,
    },
    {
        "id": "KALICONT000005635209",
        "shortTitle": "Mareyeurs-expéditeurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635209",
        "title": "Convention collective nationale des mareyeurs-expéditeurs du 15 mai 1990.  Etendue par arrêté du 14 septembre 1990 JORF 22 septembre 1990.",
        "idcc": 1589,
    },
    {
        "id": "KALICONT000005635907",
        "shortTitle": "Personnel des sociétés coopératives d'HLM",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635907",
        "title": "Convention collective nationale du personnel des sociétés coopératives d'HLM du 15 mai 1990. ",
        "idcc": 1588,
    },
    {
        "id": "KALICONT000005635436",
        "shortTitle": "Industrie de la chaussure et des articles chaussants",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635436",
        "title": "Convention collective nationale de l'industrie de la chaussure et des articles chaussants du 31 mai 1968, révisée par protocole d'accord du 7 mars 1990. Etendu par arrêté du 29 octobre 1990 JORF 1er novembre 1990.",
        "idcc": 1580,
    },
    {
        "id": "KALICONT000005635434",
        "shortTitle": "Papeterie : commerce de détail de papeterie, fournitures de bureau, bureautique et informatique, librairie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635434",
        "title": "Convention collective nationale des commerces de détail de papeterie, fournitures de bureau, de bureautique et informatique et de librairie du 15 décembre 1988.  Etendue par arrêté du 14 décembre 1989 JORF 30 décembre 1989.",
        "idcc": 1539,
    },
    {
        "id": "KALICONT000005635662",
        "shortTitle": "Cordonnerie multiservice",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635662",
        "title": "Convention collective nationale de la cordonnerie multiservice du 7 août 1989. Elargie au secteur des cordonniers industriels ",
        "idcc": 1561,
    },
    {
        "id": "KALICONT000005635944",
        "shortTitle": "Industries céramiques de France",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635944",
        "title": "Convention collective nationale relative aux conditions de travail du personnel des industries céramiques de France du 6 juillet 1989",
        "idcc": 1558,
    },
    {
        "id": "KALICONT000005635435",
        "shortTitle": "Organismes de formation",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635435",
        "title": "Convention collective nationale des organismes de formation du 10 juin 1988",
        "idcc": 1516,
    },
    {
        "id": "KALICONT000005635645",
        "shortTitle": "Commerce des articles de sport et équipements de loisirs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635645",
        "title": "Convention collective nationale du commerce des articles de sports et d'équipements de loisirs du 26 juin 1989",
        "idcc": 1557,
    },
    {
        "id": "KALICONT000005635900",
        "shortTitle": "Fabrication et commerce des produits à usage pharmaceutique, parapharmaceutique et vétérinaire",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635900",
        "title": "Convention collective nationale de la fabrication et du commerce des produits à usage pharmaceutique, parapharmaceutique et vétérinaire du 1er juin 1989.  Etendue par arrêté du 20 avril 1990 JORF 29 avril 1990",
        "idcc": 1555,
    },
    {
        "id": "KALICONT000005635177",
        "shortTitle": "Éducation, culture, loisirs et animation au service des territoires (ÉCLAT)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635177",
        "title": "Convention collective nationale des métiers de l'éducation, de la culture, des loisirs et de l'animation agissant pour l'utilité sociale et environnementale, au service des territoires (ÉCLAT) du 28 juin 1988. Étendue par arrêté du 10 janvier 1989 JORF 13 janvier 1989",
        "idcc": 1518,
    },
    {
        "id": "KALICONT000005635657",
        "shortTitle": "Distributeurs conseils hors domicile (bières, eaux minérales et de table, boissons gazeuses ou non gazeuses, boissons aux jus de fruits, sirops, jus de fruits, boissons lactées et gaz carbonique)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635657",
        "title": "Convention collective nationale des distributeurs conseils hors domicile (distributeurs CHD).  Etendue par arrêté du 4 janvier 1974 JORF 20 janvier 1974.",
        "idcc": 1536,
    },
    {
        "id": "KALICONT000005635180",
        "shortTitle": "Miroiterie (transformation et négoce du verre)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635180",
        "title": "Convention collective nationale de la miroiterie, de la transformation et du négoce du verre du 9 mars 1988",
        "idcc": 1499,
    },
    {
        "id": "KALICONT000005635871",
        "shortTitle": "Bricolage (vente au détail en libre-service)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635871",
        "title": "Convention collective nationale du bricolage (Vente au détail en libre-service) du 30 septembre 1991.  ",
        "idcc": 1606,
    },
    {
        "id": "KALICONT000005635596",
        "shortTitle": "Restauration rapide",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635596",
        "title": "Convention collective nationale de la restauration rapide du 18 mars 1988",
        "idcc": 1501,
    },
    {
        "id": "KALICONT000005635421",
        "shortTitle": "Commerce de détail alimentaire non spécialisé",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635421",
        "title": "Convention collective nationale du commerce de détail alimentaire non spécialisé du 12 janvier 2021 (Avenant n° 138 du 12 janvier 2021) - Étendue par arrêté du 17 décembre 2021 JORF 23 décembre 2021",
        "idcc": 1505,
    },
    {
        "id": "KALICONT000005635194",
        "shortTitle": "Transformation des papiers-cartons et industries connexes (OEDTAM)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635194",
        "title": "Convention collective nationale des ouvriers, employés, dessinateurs, techniciens et agents de maîtrise de la transformation des papiers et cartons et des industries connexes du 16 février 1988. Etendue par arrêté du 6 mars 1989 JORF 17 mars 1989.",
        "idcc": 1495,
    },
    {
        "id": "KALICONT000005635192",
        "shortTitle": "Production des papiers-cartons et celluloses (OEDTAM)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635192",
        "title": "Convention collective nationale des ouvriers, employés, dessinateurs, techniciens et agents de maîtrise de la production des papiers, cartons et celluloses du 20 janvier 1988.",
        "idcc": 1492,
    },
    {
        "id": "KALICONT000005635827",
        "shortTitle": "Horlogerie-bijouterie (commerce de détail)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635827",
        "title": "Convention collective nationale du commerce de détail de l'horlogerie bijouterie du 17 décembre 1987. Etendue par arrêté du 20 octobre 1988 JORF 28 octobre 1988.",
        "idcc": 1487,
    },
    {
        "id": "KALICONT000005635173",
        "shortTitle": "Bureaux d'études techniques, cabinets d'ingénieurs-conseils et sociétés de conseils",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635173",
        "title": "Convention collective nationale des bureaux d'études techniques, des cabinets d'ingénieurs-conseils et des sociétés de conseils du 15 décembre 1987. ",
        "idcc": 1486,
    },
    {
        "id": "KALICONT000005635444",
        "shortTitle": "Journalistes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635444",
        "title": "Convention collective nationale des journalistes du 1er novembre 1976, refondue le 27 octobre 1987.  Etendue par arrêté du 2 février 1988 (JO du 13 février 1988)",
        "idcc": 1480,
    },
    {
        "id": "KALICONT000005635912",
        "shortTitle": "Optique-lunetterie de détail",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635912",
        "title": "Convention collective nationale de l'optique-lunetterie de détail du 2 juin 1986.  Etendue par arrêté du 15 octobre 1986 JORF 14 décembre 1986.",
        "idcc": 1431,
    },
    {
        "id": "KALICONT000005635740",
        "shortTitle": "Réseaux de transports publics urbains de voyageurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635740",
        "title": "Convention collective nationale des réseaux de transports publics urbains de voyageurs du 11 avril 1986.  Etendue par arrêté du 25 janvier 1993 JORF 30 janvier 1993.",
        "idcc": 1424,
    },
    {
        "id": "KALICONT000005635142",
        "shortTitle": "Expédition et exportation de fruits et légumes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635142",
        "title": "Convention collective nationale des entreprises d'expédition et d'exportation de fruits et légumes du 17 décembre 1985.  Etendue par arrêté du 24 avril 1986 JORF 8 mai 1986.",
        "idcc": 1405,
    },
    {
        "id": "KALICONT000005635616",
        "shortTitle": "Ameublement (Fabrication)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635616",
        "title": "Convention collective nationale de la fabrication de l'ameublement du 14 janvier 1986.  Etendue par arrêté du 28 mai 1986 (JORF du 22 juin 1986).",
        "idcc": 1411,
    },
    {
        "id": "KALICONT000005635396",
        "shortTitle": "Installation, entretien, réparation et dépannage de matériel aéraulique, thermique et frigorifique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635396",
        "title": "Convention collective nationale des entreprises d'installation sans fabrication, y compris entretien, réparation, dépannage de matériel aéraulique, thermique, frigorifique et connexes du 21 janvier 1986. ",
        "idcc": 1412,
    },
    {
        "id": "KALICONT000005635427",
        "shortTitle": "Négoce et distribution de combustibles solides, liquides, gazeux et produits pétroliers",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635427",
        "title": "Convention collective nationale du négoce et de distribution de combustibles solides, liquides, gazeux, produits pétroliers du 20 décembre 1985",
        "idcc": 1408,
    },
    {
        "id": "KALICONT000005635473",
        "shortTitle": "Manutention et nettoyage sur les aéroports (région parisienne)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635473",
        "title": "Convention collective régionale concernant le personnel de l'industrie, de la manutention et du nettoyage sur les aéroports ouverts à la circulation publique du 1er octobre 1985. Etendue par arrêté du 16 juin 1986 JORF 24 juin 1986.",
        "idcc": 1391,
    },
    {
        "id": "KALICONT000005635267",
        "shortTitle": "Industrie du pétrole",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635267",
        "title": "Convention collective nationale de l'industrie du pétrole du 3 septembre 1985.  Etendue par arrêté du 31 juillet 1986 JORF 9 août 1986.",
        "idcc": 1388,
    },
    {
        "id": "KALICONT000005635405",
        "shortTitle": "Entreprises de prévention et de sécurité",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635405",
        "title": "Convention collective nationale des entreprises de prévention et de sécurité du 15 février 1985.  Etendue par arrêté du 25 juillet 1985 (JO du 30 juillet 1985)",
        "idcc": 1351,
    },
    {
        "id": "KALICONT000005635591",
        "shortTitle": "Quincaillerie : commerces de quincaillerie, fournitures industrielles, fers-métaux et équipements de la maison",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635591",
        "title": "Convention collective nationale des employés et agents de maîtrise des commerces de quincaillerie, fournitures industrielles, fers, métaux et équipement de la maison. Etendue par arrêté du 29 avril 1986 JORF 1er juin 1986.",
        "idcc": 1383,
    },
    {
        "id": "KALICONT000005635867",
        "shortTitle": "Tourisme social et familial",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635867",
        "title": "Convention collective nationale de tourisme social et familial du 28 juin 1979, mise à jour du 10 octobre 1984  ",
        "idcc": 1316,
    },
    {
        "id": "KALICONT000005635694",
        "shortTitle": "Restauration ferroviaire",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635694",
        "title": "Convention collective nationale de la restauration ferroviaire du 4 septembre 1984. Etendue par arrêté du 22 février 1985 JONC 7 mars 1985.",
        "idcc": 1311,
    },
    {
        "id": "KALICONT000005635373",
        "shortTitle": "Commerces de gros",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635373",
        "title": "Convention collective nationale de commerces de gros du 23 juin 1970. Etendue par arrêté du 15 juin 1972 JONC 29 août 1972. Mise à jour par accord du 27 septembre 1984 étendu par arrêté du 4 février 1985 JORF 16 février 1985.",
        "idcc": 573,
    },
    {
        "id": "KALICONT000005635203",
        "shortTitle": "Exploitation cinématographique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635203",
        "title": "Convention collective  nationale de l'exploitation cinématographique du 19 juillet 1984 ",
        "idcc": 1307,
    },
    {
        "id": "KALICONT000005635418",
        "shortTitle": "Restauration de collectivités",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635418",
        "title": "Convention collective nationale du personnel des entreprises de restauration de collectivités du 20 juin 1983. Etendue par arrêté du 2 février 1984 JONC 17 février 1984",
        "idcc": 1266,
    },
    {
        "id": "KALICONT000005635899",
        "shortTitle": "Confiserie, chocolaterie, biscuiterie (détaillants et détaillants-fabricants)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635899",
        "title": "Convention collective nationale des détaillants et détaillants-fabricants de la confiserie,  chocolaterie, biscuiterie du 1er janvier 1984.  Etendue par arrêté du 2 octobre 1984 JONC 12 octobre 1984.",
        "idcc": 1286,
    },
    {
        "id": "KALICONT000005635964",
        "shortTitle": "Entreprises artistiques et culturelles",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635964",
        "title": "Convention collective nationale pour les entreprises artistiques et culturelles du 1er janvier 1984.  Etendue par arrêté du 4 janvier 1994 JORF 26 janvier 1994.",
        "idcc": 1285,
    },
    {
        "id": "KALICONT000005635652",
        "shortTitle": "Habitat : personnels PACT et ARIM (centres pour la protection, l'amélioration et la conservation de l'habitat et associations pour la restauration immobilière)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635652",
        "title": "Convention collective nationale des personnels PACT et ARIM du 21 octobre 1983. Etendue par arrêté du 13 décembre 1988 JORF 29 décembre 1988.",
        "idcc": 1278,
    },
    {
        "id": "KALICONT000005635611",
        "shortTitle": "Pâtisserie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635611",
        "title": "Convention collective nationale de la pâtisserie du 30 juin 1983.  Etendue par arrêté du 29 décembre 1983 JONC 13 janvier 1984.",
        "idcc": 1267,
    },
    {
        "id": "KALICONT000005635384",
        "shortTitle": "Acteurs du lien social et familial (centres sociaux et socioculturels, associations d'accueil de jeunes enfants, associations de développement social local)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635384",
        "title": "Convention collective nationale des acteurs du lien social et familial : centres sociaux et socioculturels, associations d'accueil de jeunes enfants, associations de développement social local  du 4 juin 1983.  Etendue par arrêté du 22 janvier 1987 JORF 12 février 1987. (1)",
        "idcc": 1261,
    },
    {
        "id": "KALICONT000005635671",
        "shortTitle": "Thermique : équipements thermiques (OETAM, cadres, ingénieurs et assimilés)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635671",
        "title": "Convention collective nationale des cadres, ingénieurs et assimilés des entreprises de gestion d'équipements thermiques et de climatisation du 3 mai 1983. ",
        "idcc": 1256,
    },
    {
        "id": "KALICONT000005635909",
        "shortTitle": "Centres de gestion agréés",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635909",
        "title": "Convention collective nationale des centres de gestion agréés du 17 janvier 1983.",
        "idcc": 1237,
    },
    {
        "id": "KALICONT000005635251",
        "shortTitle": "Industries des tuiles et briques",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635251",
        "title": "Convention collective nationale de l'industrie des tuiles et briques du 17 février 1982",
        "idcc": 1170,
    },
    {
        "id": "KALICONT000005635409",
        "shortTitle": "Personnel des cabinets médicaux",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635409",
        "title": "Convention collective nationale du personnel des cabinets médicaux  du 14 octobre 1981",
        "idcc": 1147,
    },
    {
        "id": "KALICONT000005635191",
        "shortTitle": "Services de l'automobile (Commerce et réparation de l'automobile, du cycle et du motocycle, activités connexes, contrôle technique automobile, formation des conducteurs)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635191",
        "title": "Convention collective nationale du commerce et de la réparation de l'automobile, du cycle et du motocycle et des activités connexes, ainsi que du contrôle technique automobile du 15 janvier 1981. Etendue par arrêté du 30 octobre 1981 JONC 3 décembre 1981.",
        "idcc": 1090,
    },
    {
        "id": "KALICONT000005635910",
        "shortTitle": "Produits du sol, engrais et produits connexes : négoce et industrie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635910",
        "title": "Convention collective nationale des entreprises du négoce et de l'industrie des produits du sol, engrais et produits connexes du 2 juillet 1980.  ",
        "idcc": 1077,
    },
    {
        "id": "KALICONT000005635887",
        "shortTitle": "Horlogerie : commerce de gros, pièces détachées, accessoires et outillage",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635887",
        "title": "Convention collective nationale de l'horlogerie du 17 décembre 1979",
        "idcc": 1044,
    },
    {
        "id": "KALICONT000005635429",
        "shortTitle": "Navigation de plaisance",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635429",
        "title": "Convention collective nationale des entreprises relevant de la navigation de plaisance du 31 mars 1979.  Etendue par arrêté du 1er juin 1988 JORF 8 juin 1988.",
        "idcc": 1423,
    },
    {
        "id": "KALICONT000005635414",
        "shortTitle": "Prothésistes dentaires et personnels des laboratoires de prothèses dentaires",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635414",
        "title": "Convention collective nationale des prothésistes dentaires et des personnels des laboratoires de prothèse dentaire du 18 décembre 1978. Etendue par arrêté du 28 février 1979 JORF 17 mars 1979.",
        "idcc": 993,
    },
    {
        "id": "KALICONT000005635185",
        "shortTitle": "Avocats : personnel des cabinets",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635185",
        "title": "Convention collective nationale des avocats et de leur personnel du 20 février 1979. Etendue par arrêté du 13 novembre 1979 JONC 9 janvier 1980.",
        "idcc": 1000,
    },
    {
        "id": "KALICONT000005635452",
        "shortTitle": "Thermique : équipements thermiques (OETAM, cadres, ingénieurs et assimilés)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635452",
        "title": "Convention collective nationale des ouvriers, employés, techniciens et agents de maîtrise de l'exploitation d'équipements thermiques et de génie climatique du 7 février 1979.  ",
        "idcc": 998,
    },
    {
        "id": "KALICONT000005635660",
        "shortTitle": "Entreprises d'expertises en matière d'évaluations industrielles et commerciales",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635660",
        "title": "Convention collective nationale des entreprises d'expertises en matière d'évaluations industrielles et commerciales du 7 décembre 1976.  Etendue par arrêté du 5 juillet 1977 JONC 31 juillet 1977.",
        "idcc": 915,
    },
    {
        "id": "KALICONT000005635407",
        "shortTitle": "Handicapés : établissements et services pour les personnes inadaptées et handicapées",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635407",
        "title": "Convention collective nationale de travail des etablissements et services pour personnes inadaptées et handicapées du 15 mars 1966. Mise à jour au 15 septembre 1976.",
        "idcc": 413,
    },
    {
        "id": "KALICONT000005635265",
        "shortTitle": "Cinéma : distribution de films (employés et ouvriers, cadres et agents de maîtrise)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635265",
        "title": "Convention collective nationale des cadres et agents de maîtrise de la distribution des films de l'industrie cinématographique du 30 juin 1976.  Etendue par arrêté du 15 avril 1977 (JO du 29 mai 1977)",
        "idcc": 892,
    },
    {
        "id": "KALICONT000005635886",
        "shortTitle": "Boulangerie-pâtisserie (entreprises artisanales)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635886",
        "title": "Convention collective nationale de la boulangerie-pâtisserie du 19 mars 1976.  Etendue par arrêté du 21 juin 1978 JONC 28 juillet 1978.",
        "idcc": 843,
    },
    {
        "id": "KALICONT000005635826",
        "shortTitle": "Personnel des cabinets d'experts-comptables et de commissaires aux comptes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635826",
        "title": "Convention collective nationale des cabinets d'experts-comptables et de commissaires aux comptes du 9 décembre 1974. Etendue par arrêté du 30 mai 1975 JONC 12 juin 1975.",
        "idcc": 787,
    },
    {
        "id": "KALICONT000005635651",
        "shortTitle": "Voies ferrées d'intérêt local",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635651",
        "title": "Convention collective nationale du personnel des voies ferrées d'intérêt local du 26 septembre 1974.  Etendue par arrêté du 23 juin 1975 JORF 17 juillet 1975.",
        "idcc": 779,
    },
    {
        "id": "KALICONT000005635490",
        "shortTitle": "Pompes funèbres",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635490",
        "title": "Convention collective nationale des pompes funèbres du 1er  mars 1974.  Etendue par arrêté du 17 décembre 1993 JORF 28 janvier 1994.",
        "idcc": 759,
    },
    {
        "id": "KALICONT000005635412",
        "shortTitle": "Bijouterie, joaillerie, orfèvrerie et activités qui s'y rattachent",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635412",
        "title": "Convention collective nationale de la bijouterie, joaillerie, orfèvrerie et activités qui s'y rattachent du 5 juin 1970 (mise à jour par accord du 20 mars 1973).  Etendue par arrêté du 27 septembre 1973 (JO du 22 novembre 1973)",
        "idcc": 567,
    },
    {
        "id": "KALICONT000005635873",
        "shortTitle": "Instruments à écrire et industries connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635873",
        "title": "Convention collective nationale des instruments à écrire et des industries connexes du 13 février 1973. Etendue par arrêté du 14 septembre 1973 JONC 5 octobre 1973 rectificatif JONC 20 octobre 1973.",
        "idcc": 715,
    },
    {
        "id": "KALICONT000005635669",
        "shortTitle": "Transformation des papiers-cartons et de la pellicule cellulosique (ingénieurs et cadres)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635669",
        "title": "Convention collective nationale des ingénieurs et cadres de la transformation des papiers, cartons et de la pellicule cellulosique du 21 décembre 1972.",
        "idcc": 707,
    },
    {
        "id": "KALICONT000005635891",
        "shortTitle": "Personnel de la reprographie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635891",
        "title": "Convention collective nationale du personnel de la reprographie du 18 décembre 1972. Mise à jour en juin 1976.  Etendue par arrêté du 23 novembre 1976 JONC 19 décembre 1976.",
        "idcc": 706,
    },
    {
        "id": "KALICONT000005635440",
        "shortTitle": "Production des papiers, cartons et celluloses (Ingénieurs et cadres)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635440",
        "title": "Convention collective nationale des ingénieurs et cadres de la production des papiers, cartons et celluloses du 4 décembre 1972.",
        "idcc": 700,
    },
    {
        "id": "KALICONT000005635617",
        "shortTitle": "Maisons à succursales de vente au détail d'habillement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635617",
        "title": "Convention collective nationale des maisons à succursales de vente au détail d'habillement du 30 juin 1972.  Etendue par arrêté du 8 décembre 1972 (JO du 7 janvier 1973).",
        "idcc": 675,
    },
    {
        "id": "KALICONT000005635650",
        "shortTitle": "Industries de fabrication mécanique du verre",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635650",
        "title": "Convention collective nationale des industries de fabrication mécanique du verre du 8 juin 1972",
        "idcc": 669,
    },
    {
        "id": "KALICONT000005635631",
        "shortTitle": "Industries charcutières (salaisons, charcuteries, conserves de viandes)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635631",
        "title": "Convention collective nationale de l'industrie de la salaison, charcuterie en gros et conserves de viandes du 29 mars 1972.  Etendue par arrêté du 14 mai 1975 JORF 4 juin 1975.",
        "idcc": 1586,
    },
    {
        "id": "KALICONT000005635842",
        "shortTitle": "Métallurgie : ingénieurs et cadres",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635842",
        "title": "Convention collective nationale des ingénieurs et cadres de la métallurgie du 13 mars 1972. Etendue par arrêté du 27 avril 1973 (JO du 29 mai 1973)",
        "idcc": 650,
    },
    {
        "id": "KALICONT000005635466",
        "shortTitle": "Industries et commerce de la récupération",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635466",
        "title": "Convention collective nationale des industries et du commerce de la récupération du 6 décembre 1971.  Etendue par arrêté du 4 janvier 1974 JONC 23 janvier 1974.  Elargie par arrêté du 16 janvier 1985 JONC 25 janvier 1985.",
        "idcc": 637,
    },
    {
        "id": "KALICONT000005635394",
        "shortTitle": "Commerce succursaliste de la chaussure",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635394",
        "title": "Convention collective nationale du commerce succursaliste de la chaussure du 2 juillet 1968, mise à jour le 18 novembre 1971 (1) ",
        "idcc": 468,
    },
    {
        "id": "KALICONT000005635648",
        "shortTitle": "Industries de la sérigraphie et des procédés d'impression numérique connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635648",
        "title": "Convention collective nationale de travail des industries de la sérigraphie et des procédés d'impression numérique connexes du 23 mars 1971  ",
        "idcc": 614,
    },
    {
        "id": "KALICONT000005635702",
        "shortTitle": "Manutention ferroviaire et travaux connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635702",
        "title": "Convention collective nationale du personnel des entreprises de manutention ferroviaire et travaux connexes du 6 janvier 1970, actualisée",
        "idcc": 538,
    },
    {
        "id": "KALICONT000005635451",
        "shortTitle": "Entreprises de l'industrie et des commerces en gros des viandes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635451",
        "title": "Convention collective nationale des entreprises de l'industrie et des commerces en gros des viandes du 20 février 1969 remise à jour par accord du 9 novembre 1988.  Etendue par arrêté du 31 décembre 1971 JONC 14 janvier 1972",
        "idcc": 1534,
    },
    {
        "id": "KALICONT000005635973",
        "shortTitle": "Industries du cartonnage",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635973",
        "title": "Convention collective nationale pour le personnel des industries de cartonnage du 9 janvier 1969. Etendue par arrêté du 2 août 1971 JONC 31 août 1971 et rectificatif au JONC du 28 novembre 1971.",
        "idcc": 489,
    },
    {
        "id": "KALICONT000005635810",
        "shortTitle": "Sociétés financières",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635810",
        "title": "Convention collective nationale des sociétés financières du 22 novembre 1968",
        "idcc": 478,
    },
    {
        "id": "KALICONT000005635642",
        "shortTitle": "Remontées mécaniques et domaines skiables",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635642",
        "title": "Convention collective nationale des remontées mécaniques et domaines skiables du 15 mai 1968. (1) Etendue par arrêté du 3 février 1971 JONC 27 février 1971.",
        "idcc": 454,
    },
    {
        "id": "KALICONT000005635847",
        "shortTitle": "Agences de voyages et de tourisme : personnels, guides accompagnateurs et accompagnateurs",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635847",
        "title": "Convention collective nationale de travail des guides accompagnateurs et accompagnateurs au service des agences de voyages et de tourisme du 10 mars 1966 ",
        "idcc": 412,
    },
    {
        "id": "KALICONT000005635689",
        "shortTitle": "Industrie textile",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635689",
        "title": "Convention collective nationale de l'industrie textile du 1er  février 1951.  Etendue par arrêté du 17 décembre 1951, rectificatif du 13 janvier 1952, mise à jour le 29 mai 1979, en vigueur le 1er octobre 1979. Etendue par arrêté du 23 octobre 1979. JONC 12 janvier 1980 ",
        "idcc": 18,
    },
    {
        "id": "KALICONT000005635149",
        "shortTitle": "Industries métallurgiques, mécaniques et connexes de la région parisienne",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635149",
        "title": "Convention collective régionale des industries métallurgiques, mécaniques et connexes de la région parisienne du 16 juillet 1954. Etendue par arrêté du 11 août 1965 (JO du 25 août 1965). \nRectificatif du 10 septembre 1965. \nMise à jour par accord du 13 juillet 1973, étendu par arrêté du 10 décembre 1979 (JO du 17 janvier 1980)",
        "idcc": 54,
    },
    {
        "id": "KALICONT000005635552",
        "shortTitle": "Couture parisienne",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635552",
        "title": "Convention collective nationale de la couture parisienne du 10 juillet 1961. Etendue par arrêté du 29 novembre 1982 JONC 20 janvier 1983.",
        "idcc": 303,
    },
    {
        "id": "KALICONT000005635856",
        "shortTitle": "Plasturgie",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635856",
        "title": "Convention collective nationale de la plasturgie du 1er  juillet 1960.  Etendue par arrêté du 14 mai 1962 JONC 7 juin 1962 rectificatif 30 juin 1962.",
        "idcc": 292,
    },
    {
        "id": "KALICONT000017960049",
        "shortTitle": "Bâtiment de la région parisienne : ouvriers, employés, techniciens et agents de maîtrise, ingénieurs, assimilés et cadres",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000017960049",
        "title": "Convention collective régionale des ingénieurs, assimilés et cadres du bâtiment de la région parisienne du 12 avril 1960",
        "idcc": 1843,
    },
    {
        "id": "KALICONT000005635872",
        "shortTitle": "Transport aérien : personnel au sol",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635872",
        "title": "Convention collective nationale du personnel au sol des entreprises de transport aérien du 22 mai 1959.  Etendue par arrêté du 10 janvier 1964 JONC 21 janvier 1964 et rectificatif JONC 4 février 1964.",
        "idcc": 275,
    },
    {
        "id": "KALICONT000005635647",
        "shortTitle": "Industries de l'habillement",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635647",
        "title": "Convention collective nationale des industries de l'habillement du 17 février 1958.  Etendue par arrêté du 23 juillet 1959 JONC 8 août 1959 et rectificatif au JONC du 13 septembre 1959.",
        "idcc": 247,
    },
    {
        "id": "KALICONT000038292684",
        "shortTitle": "Personnel des organismes de sécurité sociale",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000038292684",
        "title": "Convention collective nationale de travail du personnel des organismes de sécurité sociale du 8 février 1957",
        "idcc": 218,
    },
    {
        "id": "KALICONT000005635430",
        "shortTitle": "Carrières : industries de carrières et de matériaux (UNICEM) (ouvriers, ETAM et cadres)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635430",
        "title": "Convention collective nationale des cadres des industries de carrières et matériaux du 6 décembre 1956.  Etendue par arrêté du 13 décembre 1960 JONC 21 décembre 1960 rectificatif 9 février 1961.",
        "idcc": 211,
    },
    {
        "id": "KALICONT000005635258",
        "shortTitle": "Exploitations frigorifiques",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635258",
        "title": "Convention collective nationale des exploitations frigorifiques du 10 juillet 1956.  Etendue par arrêté du 15 novembre 1961 JONC 3 décembre 1961.",
        "idcc": 200,
    },
    {
        "id": "KALICONT000005635955",
        "shortTitle": "Imprimeries de labeur et industries graphiques",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635955",
        "title": "Convention collective nationale de travail du personnel des imprimeries de labeur et des industries graphiques.  En vigueur le 1er juin 1956.  Etendue par arrêté du 22 novembre 1956 JONC 15 décembre 1956.",
        "idcc": 184,
    },
    {
        "id": "KALICONT000005635184",
        "shortTitle": "Industrie pharmaceutique",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635184",
        "title": "Convention collective nationale de l'industrie pharmaceutique du 6 avril 1956.  Etendue par arrêté du 15 novembre 1956 JORF 14 décembre 1956.",
        "idcc": 176,
    },
    {
        "id": "KALICONT000005635966",
        "shortTitle": "Travail mécanique du bois, des scieries, du négoce et de l'importation des bois",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635966",
        "title": "Convention collective nationale du travail mécanique du bois, des scieries, du négoce et de l'importation des bois du 28 novembre 1955. Étendue par arrêté du 28 mars 1956 JONC 8 avril 1956   ",
        "idcc": 158,
    },
    {
        "id": "KALICONT000005635649",
        "shortTitle": "Carrières : industries de carrières et de matériaux (UNICEM) (ouvriers, ETAM et cadres)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635649",
        "title": "Convention collective nationale relative aux conditions de travail des employés, techniciens et agents de maîtrise des industries de carrières et de matériaux du 12 juillet 1955.  Etendue par arrêté du 13 décembre 1960 JONC 21 décembre 1960 rectificatif 9 février 1961.",
        "idcc": 135,
    },
    {
        "id": "KALICONT000005635206",
        "shortTitle": "Carrières : industries de carrières et de matériaux (UNICEM) (ouvriers, ETAM et cadres)",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635206",
        "title": "Convention collective nationale relative aux conditions de travail des ouvriers des industries de carrières et de matériaux du 22 avril 1955. Etendue par arrêté du 13 décembre 1960 JONC 21 décembre 1960 rectificatif 9 février 1961.",
        "idcc": 87,
    },
    {
        "id": "KALICONT000005635630",
        "shortTitle": "Entreprises de la publicité et assimilées",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635630",
        "title": "Convention collective nationale de travail des cadres, techniciens et employés de la publicité française du 22 avril 1955. Étendue par arrêté du 29 juillet 1955 JORF 19 août 1955",
        "idcc": 86,
    },
    {
        "id": "KALICONT000005635597",
        "shortTitle": "Caoutchouc",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635597",
        "title": "Convention collective nationale du caoutchouc du 6 mars 1953. Étendue par arrêté du 29 mai 1969 JORF 18 juin 1969 ",
        "idcc": 45,
    },
    {
        "id": "KALICONT000005635613",
        "shortTitle": "Industries chimiques et connexes",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635613",
        "title": "Convention collective nationale des industries chimiques et connexes du 30 décembre 1952. Étendue par arrêté du 13 novembre 1956 JONC 12 décembre 1956",
        "idcc": 44,
    },
    {
        "id": "KALICONT000005635624",
        "shortTitle": "Transports routiers et activités auxiliaires du transport",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000005635624",
        "title": "Convention collective nationale des transports routiers et activités auxiliaires du transport du 21 décembre 1950",
        "idcc": 16,
    },
    {
        "id": "KALICONT000044349436",
        "shortTitle": "Presse quotidienne et hebdomadaire en régions",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000044349436",
        "title": "Convention collective nationale de la presse quotidienne et hebdomadaire en régions du 9 août 2021.",
        "idcc": 3242,
    },
    {
        "id": "KALICONT000043996969",
        "shortTitle": "Ciment : industrie de la fabrication des ciments",
        "url": "https://www.legifrance.gouv.fr/affichIDCC.do?idConvention=KALICONT000043996969",
        "title": "Convention collective nationale de l'industrie de la fabrication des ciments du 2 octobre 2019 - Etendue par arrêté du 30 juillet 2021 JORF 17 août 2021, modifié par arrêté du 17 sept. 2021 JORF 28 sept. 2021.",
        "idcc": 3233,
    },
]
