name: Test

on:
  workflow_dispatch:
  push:
    branches: ["*"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  test:
    name: Test publicodes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd publicodes-api
          yarn && yarn start &
          cd ..
          docker run -d -p 8083:8080 -v $PWD/nginx.conf:/etc/nginx/conf.d/default.conf nginx:alpine3.18 
          export OPENAI_URL=http://127.0.0.1:8083
          pip install poetry
          poetry install
          poetry run python src/tools.test.py
